version: '3.8'
services:
db:
image: postgres:15
restart: always
environment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: creditapp
ports:
- "5432:5432"
volumes:
- db_data:/var/lib/postgresql/data


backend:
build: .
depends_on:
- db
environment:
- DATABASE_URL=postgresql://postgres:postgres@db:5432/creditapp
- PORT=4000
ports:
- "4000:4000"
command: ["npm","run","dev"]


volumes:
db_data: